//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAruhaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.Product2Photo = new HashSet<Product2Photo>();
        }
    
        public int PhotoID { get; set; }
        public System.Guid URLCode { get; set; }
        public byte[] Image { get; set; }
        public bool IsActivePhoto { get; set; }
        public bool PhotoType { get; set; }
        public string ImagePath2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product2Photo> Product2Photo { get; set; }
    }
}
