//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAruhaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product2Photo
    {
        public int P2PID { get; set; }
        public int ProdID { get; set; }
        public int PhotoID { get; set; }
        public bool IsActiveP2P { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Product Product { get; set; }
    }
}
