//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAruhaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWithCategory
    {
        public int ProdID { get; set; }
        public int CatID { get; set; }
        public string CatName { get; set; }
        public string CatPath { get; set; }
        public Nullable<int> CatBoss { get; set; }
    }
}
