//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAruhaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Category2Product = new HashSet<Category2Product>();
            this.Product2Photo = new HashSet<Product2Photo>();
        }
    
        public int ProdID { get; set; }
        public bool IsActiveProduct { get; set; }
        public string ProdName { get; set; }
        public string ProdDescription { get; set; }
        public decimal NetPrice { get; set; }
        public decimal VAT { get; set; }
        public Nullable<decimal> BrutPrice { get; set; }
        public long ProdSeen { get; set; }
        public System.DateTime ProdCreated { get; set; }
        public System.DateTime ProdPriceChanged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category2Product> Category2Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product2Photo> Product2Photo { get; set; }
    }
}
