//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAruhaz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebShopContext : DbContext
    {
        public WebShopContext()
            : base("name=WebShopContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category2Product> Category2Product { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Product2Photo> Product2Photo { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<ProductWithphoto> ProductWithphotos { get; set; }
        public virtual DbSet<ProductWithCategory> ProductWithCategories { get; set; }
    
        public virtual int FromProdutsToCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FromProdutsToCategories");
        }
    
        public virtual int FromProdutsToPhotos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FromProdutsToPhotos");
        }
    }
}
